export const hostileIdentityFields = {
  actorDisplayName: "Forged Name",
  actorEmail: "forged@example.com",
  actorAvatarUrl: "https://example.com/forged.png",
  authName: "Legacy Name",
  authEmail: "legacy@example.com",
  authAvatarUrl: "https://example.com/legacy.png",
  userId: "attacker",
  spawnSource: "automation",
  authProvider: "github",
  authUserId: "someone-else",
  actorUserId: "someone-else",
  scmUserId: "someone-else",
  scmToken: "gho_forged",
  scmRefreshToken: "ghr_forged",
  scmTokenExpiresAt: 4_102_444_800_000,
  scmLogin: "forged-login",
  scmName: "Forged SCM Name",
  scmEmail: "forged-scm@example.com",
  scmAvatarUrl: "https://example.com/forged-scm.png",
} as const;
