#!/usr/bin/env bash
#
# The compose smoke: boot the control-plane container the way a deployment
# does, round-trip one session through it, and prove the stack came up whole.
#
# It builds the image, brings up the app with MinIO, Litestream and a stand-in
# for the Modal data plane, runs the session driver, then checks the boot-level
# invariants no unit test can see: migrations applied, the cron loop ticking,
# the global store replicating, a clean drain on SIGTERM, and a readable
# failure when a required key is missing.
#
# Everything runs locally. No cloud credentials, so this passes on a fork's
# pull request.
#
#   scripts/compose-smoke.sh
#
# Requires Docker with Compose v2 and an installed node_modules (npm ci) with
# @open-inspect/shared built.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Everything this run touches belongs to it alone.
#
# The project name is the ownership boundary: Compose would otherwise derive it
# from the checkout's directory, so the smoke would share container identities
# and the `control-plane-data` and `minio-data` volumes with a development stack
# started from the same tree, and the teardown below would delete that stack's
# data. The name is fixed rather than unique per run so a killed run's
# containers are reclaimed by the next one instead of leaking forever.
PROJECT="${SMOKE_PROJECT_NAME:-open-inspect-compose-smoke}"

# Configuration lives in a temporary file, never the checkout's `.env`: the
# teardown removes what it created, and the checkout's file is not its to
# remove. The overlay reads the same path for the app's `env_file`.
ENV_FILE="$(mktemp -t compose-smoke-env.XXXXXX)"
export SMOKE_ENV_FILE="$ENV_FILE"

COMPOSE=(docker compose --project-name "$PROJECT" --env-file "$ENV_FILE"
  -f docker-compose.yml -f docker-compose.smoke.yml)

# Overridable so the smoke can run beside a development stack on the defaults.
APP_PORT="${SMOKE_APP_PORT:-8787}"
FAKE_MODAL_PORT="${SMOKE_FAKE_MODAL_PORT:-9900}"
export SMOKE_APP_PORT="$APP_PORT" SMOKE_FAKE_MODAL_PORT="$FAKE_MODAL_PORT"
export SMOKE_MINIO_PORT="${SMOKE_MINIO_PORT:-9000}"
export SMOKE_MINIO_CONSOLE_PORT="${SMOKE_MINIO_CONSOLE_PORT:-9001}"
# Beside the driver so `ws` resolves from the repository's node_modules.
DRIVER_BUNDLE="$REPO_ROOT/packages/control-plane/test/smoke/run-smoke.bundle.mjs"
LOG_DIR="${SMOKE_LOG_DIR:-$REPO_ROOT/smoke-logs}"
FAILED=0

log() { printf '\n=== %s\n' "$1"; }

collect_logs() {
  mkdir -p "$LOG_DIR"
  for service in app minio litestream fake-modal; do
    "${COMPOSE[@]}" logs --no-color "$service" >"$LOG_DIR/$service.log" 2>&1 || true
  done
  echo "container logs written to $LOG_DIR"
}

cleanup() {
  local status=$?
  if [ "$status" -ne 0 ] || [ "$FAILED" -ne 0 ]; then
    collect_logs
    log "app log tail"
    "${COMPOSE[@]}" logs --no-color --tail 60 app || true
  fi
  "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
  rm -f "$ENV_FILE" "$DRIVER_BUNDLE"
}
trap cleanup EXIT

fail() {
  echo "FAIL: $1" >&2
  FAILED=1
  exit 1
}

# ---------------------------------------------------------------------------
# Configuration: throwaway values, generated per run.
# ---------------------------------------------------------------------------

log "writing a throwaway environment file"

key() { openssl rand -base64 32; }

cat >"$ENV_FILE" <<EOF
# Generated by scripts/compose-smoke.sh for one run. Deleted when it finishes.
DEPLOYMENT_NAME=smoke
APP_NAME=Open-Inspect Smoke
GITHUB_BOT_USERNAME=open-inspect-smoke[bot]
WEB_APP_URL=http://localhost:3000
WORKER_URL=http://app:8787
SCM_PROVIDER=github
LOG_LEVEL=info

TOKEN_ENCRYPTION_KEY=$(key)
PROVIDER_ACCOUNTS_ENCRYPTION_KEY=$(key)
REPO_SECRETS_ENCRYPTION_KEY=$(key)
BROWSER_AUTH_SECRET=$(key)
IMAGE_CALLBACK_TOKEN_PEPPER=$(key)

# The smoke's caller is a verified Slack service asserting one actor.
SERVICE_AUTH_SECRET_SLACK_BOT=$(key)
UNSAFE_ALLOW_ALL_USERS=true

SANDBOX_PROVIDER=modal
MODAL_API_SECRET=$(openssl rand -hex 32)
MODAL_WORKSPACE=smoke

OBJECT_STORE_BUCKET=media
OBJECT_STORE_REGION=us-east-1
OBJECT_STORE_ENDPOINT=http://minio:9000
OBJECT_STORE_ALLOW_HTTP=true
OBJECT_STORE_FORCE_PATH_STYLE=true
AWS_ACCESS_KEY_ID=minioadmin
AWS_SECRET_ACCESS_KEY=$(openssl rand -hex 16)
EOF

MINIO_PASSWORD="$(grep '^AWS_SECRET_ACCESS_KEY=' "$ENV_FILE" | cut -d= -f2-)"
cat >>"$ENV_FILE" <<EOF

MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$MINIO_PASSWORD
LITESTREAM_BUCKET=backups
LITESTREAM_ENDPOINT=http://minio:9000
LITESTREAM_ACCESS_KEY_ID=minioadmin
LITESTREAM_SECRET_ACCESS_KEY=$MINIO_PASSWORD
EOF

# ---------------------------------------------------------------------------
# Boot.
# ---------------------------------------------------------------------------

log "building and starting the stack"
"${COMPOSE[@]}" up -d --build --wait || fail "the stack did not become healthy"

# ---------------------------------------------------------------------------
# The session round-trip.
# ---------------------------------------------------------------------------

log "session round-trip"
# Read the one value the driver signs with, rather than sourcing the file:
# several of its values contain spaces.
SERVICE_AUTH_SECRET_SLACK_BOT="$(grep '^SERVICE_AUTH_SECRET_SLACK_BOT=' "$ENV_FILE" | cut -d= -f2-)"
export SERVICE_AUTH_SECRET_SLACK_BOT

# The driver signs with the shared package's own sig1 implementation rather
# than a second copy of the format. That package ships extensionless ESM
# imports for its bundlers, so bundle the driver the way every other consumer
# builds against it; `ws` stays external and resolves from node_modules.
npx --no-install esbuild packages/control-plane/test/smoke/run-smoke.mjs \
  --bundle --platform=node --format=esm --target=node22 --external:ws \
  --outfile="$DRIVER_BUNDLE" --log-level=warning || fail "could not bundle the smoke driver"

CONTROL_PLANE_URL="http://localhost:$APP_PORT" \
  FAKE_MODAL_URL="http://localhost:$FAKE_MODAL_PORT" \
  node "$DRIVER_BUNDLE" || fail "the session round-trip failed"

# ---------------------------------------------------------------------------
# Boot-level invariants: what only a booted container can show.
# ---------------------------------------------------------------------------

# The scheduler tick runs on the minute, so the wait is bounded by one slot
# plus room for a slow runner. Everything above already ran, so most of that
# minute has usually passed by the time we get here.
log "scheduled work"
TICK_DEADLINE=$((SECONDS + 90))
until "${COMPOSE[@]}" logs --no-color app | grep -q "scheduler.tick_complete"; do
  [ "$SECONDS" -lt "$TICK_DEADLINE" ] || fail "the cron loop never completed a tick"
  sleep 3
done
echo "  ok  the cron loop ticked"

log "replication"
"${COMPOSE[@]}" logs --no-color litestream | grep -q "snapshot written" ||
  fail "Litestream never wrote a snapshot of the global store"
echo "  ok  Litestream replicated the global store"

log "clean shutdown"
"${COMPOSE[@]}" stop app >/dev/null 2>&1 || true
APP_EXIT="$("${COMPOSE[@]}" ps -a --format json app | node -e '
  const chunks = [];
  process.stdin.on("data", (c) => chunks.push(c));
  process.stdin.on("end", () => {
    const text = chunks.join("").trim();
    // Compose emits either one JSON object or one per line depending on version.
    const rows = text.startsWith("[") ? JSON.parse(text) : text.split("\n").filter(Boolean).map((l) => JSON.parse(l));
    process.stdout.write(String(rows[0]?.ExitCode ?? "missing"));
  });
')"
[ "$APP_EXIT" = "0" ] || fail "the host exited with $APP_EXIT on SIGTERM instead of draining cleanly"
APP_LOG="$("${COMPOSE[@]}" logs --no-color app)"
# The structured field, not the message: `node_host.stopped` is a prefix of
# `node_host.stopped_unclean`, and that unclean path still exits 0, so a
# substring match would report abandoned work as a clean drain.
grep -q '"event":"node_host.stopped"' <<<"$APP_LOG" ||
  fail "the host never logged a completed shutdown"
if grep -q "node_host.stopped_unclean" <<<"$APP_LOG"; then
  fail "the host abandoned work during shutdown"
fi
echo "  ok  the host drained and exited 0 on SIGTERM"

# ---------------------------------------------------------------------------
# A missing required key must fail the boot with something a reader can act on.
# ---------------------------------------------------------------------------

# Bounded, because the failure this guards against is a host that accepts the
# blank key and serves: that would otherwise hang until the job timeout.
log "missing required configuration"
MISSING_LOG="$(mktemp -t compose-smoke-missing.XXXXXX)"
"${COMPOSE[@]}" run --rm --no-deps -e TOKEN_ENCRYPTION_KEY= app >"$MISSING_LOG" 2>&1 &
MISSING_PID=$!
MISSING_DEADLINE=$((SECONDS + 60))
while kill -0 "$MISSING_PID" 2>/dev/null; do
  if [ "$SECONDS" -ge "$MISSING_DEADLINE" ]; then
    kill "$MISSING_PID" 2>/dev/null || true
    fail "a blank TOKEN_ENCRYPTION_KEY did not stop the boot within 60s"
  fi
  sleep 1
done
MISSING_STATUS=0
wait "$MISSING_PID" || MISSING_STATUS=$?
MISSING_OUTPUT="$(cat "$MISSING_LOG")"
rm -f "$MISSING_LOG"
[ "$MISSING_STATUS" -ne 0 ] ||
  fail "a blank TOKEN_ENCRYPTION_KEY let the host boot: $MISSING_OUTPUT"
grep -q "TOKEN_ENCRYPTION_KEY" <<<"$MISSING_OUTPUT" ||
  fail "the failed boot did not name the missing key: $MISSING_OUTPUT"
echo "  ok  a blank required key fails the boot and names itself"

log "compose smoke passed"
