/**
 * Sandbox provider interface.
 *
 * Defines a pluggable abstraction for sandbox providers (Modal, Fly.io, Docker, etc.)
 * enabling unit testing and future provider support.
 */

import type { ImageBuildScopeKind } from "@open-inspect/shared/types/image-builds";
import type { SandboxSettings } from "@open-inspect/shared/types/integrations";
import type { CorrelationContext } from "../logger";
import { RequestDeadlineError } from "./request-deadline";
import type { McpServerConfig } from "@open-inspect/shared/types/integrations";

/** Default sandbox lifetime in seconds (2 hours). */
export const DEFAULT_SANDBOX_TIMEOUT_SECONDS = 7200;

/**
 * Provider-neutral configuration for triggering an image build inside a
 * provider session. Every supported provider follows the same
 * create-bind-launch contract: create the build sandbox, bind its provider
 * session id via `onProviderSessionCreated`, then launch the build runtime.
 * Providers that need extra fields extend this type (see
 * ModalImageBuildTriggerConfig).
 */
export interface ImageBuildProviderTriggerConfig {
  buildId: string;
  scopeKind: ImageBuildScopeKind;
  /** Build scope id; used only for sandbox naming/labels. */
  scopeId: string;
  /** Repositories in position order ([0] = primary), cloned at their base branches. */
  repositories: Array<{ repoOwner: string; repoName: string; baseBranch: string }>;
  callbackUrl: string;
  failureCallbackUrl: string;
  callbackToken: string;
  userEnvVars?: Record<string, string>;
  cloneToken?: string;
  buildExecutionTimeoutSeconds: number;
  /**
   * Provider-session lifetime in seconds, including deferred finalization
   * headroom. Always resolved by the adapter layer
   * (resolveImageBuildProviderSessionTimeoutSeconds) — providers apply it
   * verbatim instead of choosing their own default.
   */
  providerSessionTimeoutSeconds: number;
  onProviderSessionCreated: (providerSessionId: string) => Promise<void>;
  correlation: CorrelationContext;
}

/**
 * Capabilities supported by a sandbox provider.
 * Providers can support different feature sets.
 */
export interface SandboxProviderCapabilities {
  /** Whether explicit sandbox session lifetimes are enforced by this provider. */
  supportsSandboxTimeout: boolean;
  /** Whether the provider supports filesystem snapshots */
  supportsSnapshots: boolean;
  /** Whether the provider supports restoring from snapshots */
  supportsRestore: boolean;
  /** Whether the provider can resume a previously stopped sandbox in place */
  supportsPersistentResume?: boolean;
  /** Whether the provider can stop a sandbox explicitly via API */
  supportsExplicitStop?: boolean;
}

/**
 * One member repository of a session, in position order (first = primary).
 * Mirrors the runtime's SessionRepositoryConfig, whose snake_case wire form
 * (with baseBranch renamed to `branch`) is produced by
 * toRepositoryConfigPayload.
 */
export interface SessionRepositoryInfo {
  repoOwner: string;
  repoName: string;
  /** Base branch to clone (resolved at session create; never null). */
  baseBranch: string;
  /** Immutable session-start commit used by the Changes capture protocol. */
  baseSha?: string | null;
}

/**
 * Configuration for creating a new sandbox.
 */
export interface CreateSandboxConfig {
  /** Session ID for WebSocket routing */
  sessionId: string;
  /** Expected sandbox ID (generated by control plane) */
  sandboxId: string;
  /** Repository owner */
  repoOwner: string | null;
  /** Repository name */
  repoName: string | null;
  /** Control plane URL for sandbox callbacks */
  controlPlaneUrl: string;
  /** Authentication token for sandbox */
  sandboxAuthToken: string;
  /** LLM provider (e.g., "anthropic") */
  provider: string;
  /** LLM model (e.g., "claude-sonnet-4-5") */
  model: string;
  /** User-provided environment variables (repo secrets) */
  userEnvVars?: Record<string, string>;
  /** Whether Anthropic OAuth is configured in control-plane secrets */
  anthropicOauthEnabled?: boolean;
  /** OpenCode session ID for resumption */
  opencodeSessionId?: string;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /**
   * Opaque provider image ID of a pre-built image — a repo image for
   * single-repo sessions, an environment image for environment sessions.
   * Both boot through the same provider plumbing (FROM_REPO_IMAGE flags).
   */
  prebuiltImageId?: string | null;
  /** Git SHA the image was built from (the primary repository's for environment images) */
  prebuiltImageSha?: string | null;
  /** Sandbox lifetime in seconds. Defaults to DEFAULT_SANDBOX_TIMEOUT_SECONDS on Modal. */
  timeoutSeconds?: number;
  /** Git branch to work on (defaults to repo's default branch) */
  branch?: string | null;
  /** Whether to enable code-server (browser-based editor) in the sandbox */
  codeServerEnabled?: boolean;
  /** Whether to enable browser-based VNC access to the sandbox */
  vncEnabled?: boolean;
  /**
   * Whether to install the agent-initiated slack-notify tool. Fixed for the
   * lifetime of the sandbox; per-call authorization is re-evaluated by the
   * control-plane endpoint.
   */
  agentSlackNotifyEnabled?: boolean;
  /** MCP servers to inject into the agent session */
  mcpServers?: McpServerConfig[];
  /** Sandbox settings (tunnel ports, etc.) resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /**
   * Ordered member list for multi-repo sessions. Only set when the session
   * has more than one member — single-repo sessions keep the scalar
   * repoOwner/repoName/branch wire form (the runtime synthesizes its
   * one-entry list from them). Working-branch names are not part of this
   * config: they are derived lazily at PR-creation time
   * (pull-request-service) and travel in per-repo push specs.
   */
  repositories?: SessionRepositoryInfo[];
}

/** Complete browser-desktop access credential returned by sandbox providers. */
export interface VncAccess {
  url: string;
  password: string;
}

/** Build a complete VNC access credential, or omit incomplete provider data. */
export function createVncAccess(
  url: string | undefined,
  password: string | undefined
): VncAccess | undefined {
  return url && password ? { url, password } : undefined;
}

/**
 * Result of creating a sandbox.
 */
export interface CreateSandboxResult {
  /** The sandbox ID (should match expected ID from config) */
  sandboxId: string;
  /** Provider's internal object ID (e.g., Modal's object ID for snapshot API) */
  providerObjectId?: string;
  /** Initial sandbox status */
  status: string;
  /** Creation timestamp */
  createdAt: number;
  /** Code-server tunnel URL (if available) */
  codeServerUrl?: string;
  /** Code-server password (if available) */
  codeServerPassword?: string;
  /** ttyd proxy tunnel URL (if available) */
  ttydUrl?: string;
  /** Complete browser-based VNC credential (if available) */
  vncAccess?: VncAccess;
  /** Tunnel URLs for extra ports (port -> URL mapping) */
  tunnelUrls?: Record<string, string>;
}

/**
 * Configuration for restoring a sandbox from a snapshot.
 */
export interface RestoreConfig {
  /** Snapshot image ID to restore from */
  snapshotImageId: string;
  /** Session ID for WebSocket routing */
  sessionId: string;
  /** Expected sandbox ID */
  sandboxId: string;
  /** Authentication token for sandbox */
  sandboxAuthToken: string;
  /** Control plane URL for sandbox callbacks */
  controlPlaneUrl: string;
  /** Repository owner */
  repoOwner: string | null;
  /** Repository name */
  repoName: string | null;
  /** LLM provider (e.g., "anthropic") */
  provider: string;
  /** LLM model (e.g., "claude-sonnet-4-5") */
  model: string;
  /** User-provided environment variables (repo secrets) */
  userEnvVars?: Record<string, string>;
  /** Whether Anthropic OAuth is configured in control-plane secrets */
  anthropicOauthEnabled?: boolean;
  /** Sandbox lifetime in seconds. Defaults to DEFAULT_SANDBOX_TIMEOUT_SECONDS. */
  timeoutSeconds?: number;
  /** Git branch to work on (defaults to repo's default branch) */
  branch?: string | null;
  /** MCP servers to inject into the sandbox */
  mcpServers?: McpServerConfig[];
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Whether to enable code-server (browser-based editor) in the sandbox */
  codeServerEnabled?: boolean;
  /** Whether to enable browser-based VNC access to the sandbox */
  vncEnabled?: boolean;
  /** Resolved fresh on each restore — see CreateSandboxConfig. */
  agentSlackNotifyEnabled?: boolean;
  /** Sandbox settings (tunnel ports, etc.) resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /** Multi-repo member list — see CreateSandboxConfig. */
  repositories?: SessionRepositoryInfo[];
}

/**
 * Result of restoring a sandbox from a snapshot.
 */
export interface RestoreResult {
  /** Whether the restore succeeded */
  success: boolean;
  /** Sandbox ID if successful */
  sandboxId?: string;
  /** Provider's internal object ID (e.g., Modal's object ID for snapshot API) */
  providerObjectId?: string;
  /** Error message if failed */
  error?: string;
  /** Code-server tunnel URL (if available) */
  codeServerUrl?: string;
  /** Code-server password (if available) */
  codeServerPassword?: string;
  /** ttyd proxy tunnel URL (if available) */
  ttydUrl?: string;
  /** Complete browser-based VNC credential (if available) */
  vncAccess?: VncAccess;
  /** Tunnel URLs for extra ports (port -> URL mapping) */
  tunnelUrls?: Record<string, string>;
}

/**
 * Configuration for taking a sandbox snapshot.
 */
export interface SnapshotConfig {
  /** Provider's internal object ID (e.g., Modal's object ID) */
  providerObjectId: string;
  /** Session ID for context */
  sessionId: string;
  /** Reason for the snapshot (e.g., "inactivity_timeout", "execution_complete") */
  reason: string;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Optional caller deadline for long-running provider artifact creation. */
  signal?: AbortSignal;
}

/**
 * Result of taking a sandbox snapshot.
 */
export interface SnapshotResult {
  /** Whether the snapshot succeeded */
  success: boolean;
  /** Snapshot image ID if successful */
  imageId?: string;
  /** Error message if failed */
  error?: string;
}

/**
 * Configuration for resuming a previously stopped sandbox.
 */
export interface ResumeConfig {
  /** Provider's internal object ID (e.g., Daytona sandbox ID) */
  providerObjectId: string;
  /** Session ID for context */
  sessionId: string;
  /** Control-plane logical sandbox ID used for bridge auth */
  sandboxId: string;
  /** Sandbox lifetime in seconds from control-plane policy */
  timeoutSeconds?: number;
  /** Whether code-server should be exposed */
  codeServerEnabled?: boolean;
  /** Whether browser-based VNC access should be exposed */
  vncEnabled?: boolean;
  /** Sandbox settings (tunnel ports, etc.) resolved from integration settings */
  sandboxSettings?: SandboxSettings;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
}

/**
 * Result of resuming a previously stopped sandbox.
 */
export interface ResumeResult {
  /** Whether the resume succeeded */
  success: boolean;
  /** Provider's internal object ID, if it changed during recovery */
  providerObjectId?: string;
  /** Error message if resume failed */
  error?: string;
  /** Whether the caller should fall back to a fresh create */
  shouldSpawnFresh?: boolean;
  /** Code-server tunnel URL (if available) */
  codeServerUrl?: string;
  /** Code-server password (if available) */
  codeServerPassword?: string;
  /** Complete browser-based VNC credential (if available) */
  vncAccess?: VncAccess;
  /** Tunnel URLs for extra ports (port -> URL mapping) */
  tunnelUrls?: Record<string, string>;
}

/**
 * Configuration for explicitly stopping a sandbox.
 */
export interface StopConfig {
  /** Provider's internal object ID (e.g., Daytona sandbox ID) */
  providerObjectId: string;
  /** Session ID for context */
  sessionId: string;
  /** Reason for the stop operation */
  reason: string;
  /** Correlation context for downstream tracing */
  correlation?: CorrelationContext;
  /** Optional caller deadline for provider cleanup. */
  signal?: AbortSignal;
}

/**
 * Result of explicitly stopping a sandbox.
 */
export interface StopResult {
  /** Whether the stop succeeded */
  success: boolean;
  /** Error message if stop failed */
  error?: string;
}

/**
 * Error classification for circuit breaker decisions.
 *
 * Only permanent failures should count toward the circuit breaker threshold.
 * Transient failures (network issues, timeouts) are logged but don't trip the breaker.
 *
 * Transient errors (do NOT count toward circuit breaker):
 * - ETIMEDOUT, ECONNRESET, ECONNREFUSED
 * - HTTP 502, 503, 504 (Bad Gateway, Service Unavailable, Gateway Timeout)
 * - "fetch failed" / network errors
 *
 * Permanent errors (DO count toward circuit breaker):
 * - HTTP 400, 401, 403, 422 (Bad Request, Unauthorized, Forbidden, Unprocessable)
 * - Invalid configuration
 * - Resource quota exceeded
 */
export type SandboxErrorType = "transient" | "permanent";

/**
 * Custom error class for sandbox provider operations.
 *
 * Includes error type classification for circuit breaker handling.
 * The circuit breaker only counts permanent errors toward its threshold.
 */
export class SandboxProviderError extends Error {
  constructor(
    message: string,
    public readonly errorType: SandboxErrorType,
    public readonly cause?: Error
  ) {
    super(message);
    this.name = "SandboxProviderError";
    // Maintain proper stack trace in V8 environments
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, SandboxProviderError);
    }
  }

  /**
   * Check if an HTTP status code indicates a transient error.
   */
  static isTransientStatus(status: number): boolean {
    return status === 502 || status === 503 || status === 504;
  }

  /**
   * Check if an error is likely a transient network error.
   */
  static isTransientNetworkError(error: unknown): boolean {
    if (error instanceof RequestDeadlineError) return true;
    if (error instanceof Error) {
      const message = error.message.toLowerCase();
      return (
        message.includes("fetch failed") ||
        message.includes("etimedout") ||
        message.includes("econnreset") ||
        message.includes("econnrefused") ||
        message.includes("network") ||
        message.includes("timeout")
      );
    }
    return false;
  }

  /**
   * Create a SandboxProviderError from a fetch error or HTTP response.
   */
  static fromFetchError(message: string, error: unknown, status?: number): SandboxProviderError {
    // Classify based on HTTP status if available
    if (status !== undefined) {
      const errorType = SandboxProviderError.isTransientStatus(status) ? "transient" : "permanent";
      return new SandboxProviderError(
        message,
        errorType,
        error instanceof Error ? error : undefined
      );
    }

    // Classify based on error type
    const errorType = SandboxProviderError.isTransientNetworkError(error)
      ? "transient"
      : "permanent";
    return new SandboxProviderError(message, errorType, error instanceof Error ? error : undefined);
  }
}

/**
 * Sandbox provider interface.
 *
 * Defines the contract for sandbox lifecycle operations.
 * Implementations wrap provider-specific APIs (Modal, Fly.io, Docker, etc.)
 *
 * Error handling:
 * - Methods should throw SandboxProviderError with appropriate errorType
 * - "transient" errors (network issues) don't count toward circuit breaker
 * - "permanent" errors (config issues) do count toward circuit breaker
 *
 * @example
 * ```typescript
 * const provider: SandboxProvider = new ModalSandboxProvider(client);
 *
 * try {
 *   const result = await provider.createSandbox(config);
 *   console.log("Created:", result.sandboxId);
 * } catch (e) {
 *   if (e instanceof SandboxProviderError && e.errorType === "permanent") {
 *     // Increment circuit breaker
 *   }
 *   // Both types set sandbox status to "failed"
 * }
 * ```
 */
export interface SandboxProvider {
  /** Provider name for logging and debugging */
  readonly name: string;

  /** Provider capabilities */
  readonly capabilities: SandboxProviderCapabilities;

  /**
   * Create a new sandbox.
   *
   * @param config - Sandbox configuration
   * @returns Creation result with sandbox ID and status
   * @throws SandboxProviderError with errorType for circuit breaker handling
   */
  createSandbox(config: CreateSandboxConfig): Promise<CreateSandboxResult>;

  /**
   * Restore a sandbox from a filesystem snapshot.
   *
   * Only available if `capabilities.supportsRestore` is true.
   *
   * @param config - Restore configuration with snapshot image ID
   * @returns Result indicating success or failure
   * @throws SandboxProviderError with errorType for circuit breaker handling
   */
  restoreFromSnapshot?(config: RestoreConfig): Promise<RestoreResult>;

  /**
   * Resume a previously stopped sandbox in place.
   *
   * Only available if `capabilities.supportsPersistentResume` is true.
   */
  resumeSandbox?(config: ResumeConfig): Promise<ResumeResult>;

  /**
   * Take a filesystem snapshot of the sandbox.
   *
   * Only available if `capabilities.supportsSnapshots` is true.
   *
   * @param config - Snapshot configuration with provider object ID
   * @returns Result with snapshot image ID if successful
   * @throws SandboxProviderError with errorType for error handling
   */
  takeSnapshot?(config: SnapshotConfig): Promise<SnapshotResult>;

  /**
   * Stop a sandbox explicitly via the provider API.
   *
   * Only available if `capabilities.supportsExplicitStop` is true.
   */
  stopSandbox?(config: StopConfig): Promise<StopResult>;
}
